hw3
MoniekNK/goit-node-hw-02 pull request #1
Opened 2024-02-07 22:27 UTC by MoniekNK

2024-02-09 16:00 UTC, KamilMr requested changes
W komentarzach sugestie.

2024-02-09 16:00 UTC, KamilMr commented on app.js
> +const startServer = (port) => {
TEgo nie potrzebujesz prawda? Mozna usunąć bo  w server.js juz masz app.listen

2024-02-09 16:00 UTC, KamilMr commented on models/contact.js
Ten plik pusty warto usunac jak nic nie ma? :)

2024-02-09 16:00 UTC, KamilMr commented on routes/api.js/contacts.js
> +const listContacts = async () => {
Hmm chyba tego nie uzywasz prawda? Ten plik jest w folderze api.js tak nie piszemy folderów z extensions.

2024-02-09 16:00 UTC, KamilMr commented on app.js
> +} = require("./routes/api.js/contacts");
```suggestion
} = require("./routes/api/contacts");
```
To extension nie powinno byc. W db.js masz jedno miejsce gdzie masz metody a tu importujesz z innego miejsca.

2024-02-09 16:00 UTC, KamilMr commented on app.js
> +});
```suggestion
app.get("/api/contacts", async (req, res) => {
  try {
    const contacts = await listContacts();
    res.json(contacts);
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Internal Server Error" });
  }
});
```
Te routes powinny być przekazane do folderu routes w pliku contacts.js

2024-02-09 16:00 UTC, KamilMr commented on app.js
> +});
I importowane tutaj 
```
app.use('/contacts', contactsRoute);
```

2024-02-09 16:00 UTC, KamilMr commented on app.js
> +});
Bo jak stworzyłaś folder routes to tam powinny byc routes.

2024-02-10 21:50 UTC, merged

2024-02-10 21:51 UTC, MoniekNK commented
Proszę o sprawdzenie kodu. Dziękuje!