New
MoniekNK/goit-node-hw-02 pull request #4
Opened 2024-03-03 23:32 UTC by MoniekNK

Najnowsza wersja zadania

2024-03-04 15:26 UTC, KamilMr commented
Musisz konflikty rozwiązać przed mergowaniem.

2024-03-04 15:35 UTC, KamilMr requested changes
Hej Monika,

Zanim przejdziesz dalej, ważne jest rozwiązanie konfliktów w repozytorium. Upewnij się, że twoje zmiany nie kolidują z istniejącym kodem. Co do zmian, które wprowadziłaś, zwróć uwagę, aby były one związane wyłącznie z obecnym zadaniem. Jeśli dodajesz coś, co wykracza poza zakres zadania, najlepiej to zrobić w oddzielnym branchu lub Pull Requeście.

Ponadto, zalecam podzielenie przyszłych zmian na mniejsze commity. Jeden commit na dużą ilość zmian utrudnia śledzenie postępów i rozumienie historii projektu. Lepszą praktyką jest tworzenie oddzielnych commitów dla każdej logicznie odseparowanej zmiany lub ulepszenia.

Pozdrawiam i powodzenia :)

2024-03-04 15:35 UTC, KamilMr commented on .gitignore
> +.SEND_GRID_BASE_URL
To nie tutaj, to jest nazwa stałej która powinna byc w .env a nie w .gitignore

2024-03-05 13:56 UTC, MoniekNK commented
.

2024-03-06 13:04 UTC, closed without merging